[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-args=-Tsrc/linker.ld",
]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../vendor"
